# Base commodities (extracted)
PlanetaryCommodity.find_or_create_by!(id: 2073,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Microorganisms')
PlanetaryCommodity.find_or_create_by!(id: 2267,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Base Metals')
PlanetaryCommodity.find_or_create_by!(id: 2268,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Aqueous Liquids')
PlanetaryCommodity.find_or_create_by!(id: 2270,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Noble Metals')
PlanetaryCommodity.find_or_create_by!(id: 2272,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Heavy Metals')
PlanetaryCommodity.find_or_create_by!(id: 2286,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Planktic Colonies')
PlanetaryCommodity.find_or_create_by!(id: 2287,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Complex Organisms')
PlanetaryCommodity.find_or_create_by!(id: 2288,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Carbon Compounds')
PlanetaryCommodity.find_or_create_by!(id: 2305,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Autotrophs')
PlanetaryCommodity.find_or_create_by!(id: 2306,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Non-CS Crystals')
PlanetaryCommodity.find_or_create_by!(id: 2307,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Felsic Magma')
PlanetaryCommodity.find_or_create_by!(id: 2308,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Suspended Plasma')
PlanetaryCommodity.find_or_create_by!(id: 2309,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Ionic Solutions')
PlanetaryCommodity.find_or_create_by!(id: 2310,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Noble Gas')
PlanetaryCommodity.find_or_create_by!(id: 2311,   tier: 0, volume: 0.01, batch_size: 1,  input: nil, name: 'Reactive Gas')

# Tier 1: Processed from base commodities, used in tier 2 production
PlanetaryCommodity.find_or_create_by!(id: 2389,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 122, name: 'Plasmoids')
PlanetaryCommodity.find_or_create_by!(id: 2390,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 123, name: 'Electrolytes')
PlanetaryCommodity.find_or_create_by!(id: 2392,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 125, name: 'Oxidizing Compound')
PlanetaryCommodity.find_or_create_by!(id: 2393,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 131, name: 'Bacteria')
PlanetaryCommodity.find_or_create_by!(id: 2395,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 133, name: 'Proteins')
PlanetaryCommodity.find_or_create_by!(id: 2396,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 134, name: 'Biofuels')
PlanetaryCommodity.find_or_create_by!(id: 2397,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 135, name: 'Industrial Fibers')
PlanetaryCommodity.find_or_create_by!(id: 2398,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 126, name: 'Reactive Metals')
PlanetaryCommodity.find_or_create_by!(id: 2399,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 127, name: 'Precious Metals')
PlanetaryCommodity.find_or_create_by!(id: 2400,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 128, name: 'Toxic Metals')
PlanetaryCommodity.find_or_create_by!(id: 2401,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 129, name: 'Chiral Structures')
PlanetaryCommodity.find_or_create_by!(id: 3645,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 72,  name: 'Water')
PlanetaryCommodity.find_or_create_by!(id: 3683,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 124, name: 'Oxygen')
PlanetaryCommodity.find_or_create_by!(id: 3779,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 132, name: 'Biomass')
PlanetaryCommodity.find_or_create_by!(id: 9828,   tier: 1, volume: 0.38, batch_size: 20, input: nil, schematic_id: 130, name: 'Silicon')

# Tier 2: Processed from tier 1 commodities, each requires 2 inputs
PlanetaryCommodity.find_or_create_by!(id: 44,     tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 75,  name: 'Enriched Uranium')
PlanetaryCommodity.find_or_create_by!(id: 2312,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 87,  name: 'Supertensile Plastics')
PlanetaryCommodity.find_or_create_by!(id: 2317,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 69,  name: 'Oxides')
PlanetaryCommodity.find_or_create_by!(id: 2319,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 86,  name: 'Test Cultures')
PlanetaryCommodity.find_or_create_by!(id: 2321,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 88,  name: 'Polyaramids')
PlanetaryCommodity.find_or_create_by!(id: 2327,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 80,  name: 'Microfiber Shielding')
PlanetaryCommodity.find_or_create_by!(id: 2328,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 121, name: 'Water-Cooled CPU')
PlanetaryCommodity.find_or_create_by!(id: 2329,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 79,  name: 'Biocells')
PlanetaryCommodity.find_or_create_by!(id: 2463,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 78,  name: 'Nanites')
PlanetaryCommodity.find_or_create_by!(id: 3689,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 73,  name: 'Mechanical Parts')
PlanetaryCommodity.find_or_create_by!(id: 3691,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 68,  name: 'Synthetic Oil')
PlanetaryCommodity.find_or_create_by!(id: 3693,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 82,  name: 'Fertilizer')
PlanetaryCommodity.find_or_create_by!(id: 3695,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 85,  name: 'Polytextiles')
PlanetaryCommodity.find_or_create_by!(id: 3697,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 70,  name: 'Silicate Glass')
PlanetaryCommodity.find_or_create_by!(id: 3725,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 84,  name: 'Livestock')
PlanetaryCommodity.find_or_create_by!(id: 3775,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 81,  name: 'Viral Agent')
PlanetaryCommodity.find_or_create_by!(id: 3828,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 74,  name: 'Construction Blocks')
PlanetaryCommodity.find_or_create_by!(id: 9830,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 67,  name: 'Rocket Fuel')
PlanetaryCommodity.find_or_create_by!(id: 9832,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 66,  name: 'Coolant')
PlanetaryCommodity.find_or_create_by!(id: 9836,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 76,  name: 'Consumer Electronics')
PlanetaryCommodity.find_or_create_by!(id: 9838,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 65,  name: 'Superconductors')
PlanetaryCommodity.find_or_create_by!(id: 9840,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 71,  name: 'Transmitter')
PlanetaryCommodity.find_or_create_by!(id: 9842,   tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 77,  name: 'Miniature Electronics')
PlanetaryCommodity.find_or_create_by!(id: 15_317, tier: 2, volume: 1.5,  batch_size: 5,  input: nil, schematic_id: 83,  name: 'Genetically Enhanced Livestock')

# Tier 3: Processed from tier 2 commodities, each requires 2-3 inputs
PlanetaryCommodity.find_or_create_by!(id: 2344,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 90,  name: 'Condensates')
PlanetaryCommodity.find_or_create_by!(id: 2345,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 91,  name: 'Camera Drones')
PlanetaryCommodity.find_or_create_by!(id: 2346,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 92,  name: 'Synthetic Synapses')
PlanetaryCommodity.find_or_create_by!(id: 2348,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 95,  name: 'Gel-Matrix Biopaste')
PlanetaryCommodity.find_or_create_by!(id: 2349,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 96,  name: 'Supercomputers')
PlanetaryCommodity.find_or_create_by!(id: 2351,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 98,  name: 'Smartfab Units')
PlanetaryCommodity.find_or_create_by!(id: 2352,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 99,  name: 'Nuclear Reactors')
PlanetaryCommodity.find_or_create_by!(id: 2354,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 102, name: 'Neocoms')
PlanetaryCommodity.find_or_create_by!(id: 2358,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 104, name: 'Biotech Research Reports')
PlanetaryCommodity.find_or_create_by!(id: 2360,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 106, name: 'Industrial Explosives')
PlanetaryCommodity.find_or_create_by!(id: 2361,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 107, name: 'Hermetic Membranes')
PlanetaryCommodity.find_or_create_by!(id: 2366,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 110, name: 'Hazmat Detection Systems')
PlanetaryCommodity.find_or_create_by!(id: 2367,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 111, name: 'Cryoprotectant Solution')
PlanetaryCommodity.find_or_create_by!(id: 9834,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 100, name: 'Guidance Systems')
PlanetaryCommodity.find_or_create_by!(id: 9846,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 103, name: 'Planetary Vehicles')
PlanetaryCommodity.find_or_create_by!(id: 9848,   tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 97,  name: 'Robotics')
PlanetaryCommodity.find_or_create_by!(id: 12_836, tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 108, name: 'Transcranial Microcontrollers')
PlanetaryCommodity.find_or_create_by!(id: 17_136, tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 89,  name: 'Ukomi Superconductors')
PlanetaryCommodity.find_or_create_by!(id: 17_392, tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 109, name: 'Data Chips')
PlanetaryCommodity.find_or_create_by!(id: 17_898, tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 94,  name: 'High-Tech Transmitters')
PlanetaryCommodity.find_or_create_by!(id: 28_974, tier: 3, volume: 6,    batch_size: 3,  input: nil, schematic_id: 105, name: 'Vaccines')

# Tier 4: Processed from tier 1/3 commodities, each requires 3 inputs
PlanetaryCommodity.find_or_create_by!(id: 2867,   tier: 4, volume: 100,  batch_size: 1,  input: nil, schematic_id: 117, name: 'Broadcast Node')
PlanetaryCommodity.find_or_create_by!(id: 2868,   tier: 4, volume: 100,  batch_size: 1,  input: nil, schematic_id: 118, name: 'Integrity Response Drones')
PlanetaryCommodity.find_or_create_by!(id: 2869,   tier: 4, volume: 100,  batch_size: 1,  input: nil, schematic_id: 114, name: 'Nano-Factory')
PlanetaryCommodity.find_or_create_by!(id: 2870,   tier: 4, volume: 100,  batch_size: 1,  input: nil, schematic_id: 112, name: 'Organic Mortar Applicators')
PlanetaryCommodity.find_or_create_by!(id: 2871,   tier: 4, volume: 100,  batch_size: 1,  input: nil, schematic_id: 116, name: 'Recursive Computing Module')
PlanetaryCommodity.find_or_create_by!(id: 2872,   tier: 4, volume: 100,  batch_size: 1,  input: nil, schematic_id: 115, name: 'Self-Harmonizing Power Core')
PlanetaryCommodity.find_or_create_by!(id: 2875,   tier: 4, volume: 100,  batch_size: 1,  input: nil, schematic_id: 113, name: 'Sterile Conduits')
PlanetaryCommodity.find_or_create_by!(id: 2876,   tier: 4, volume: 100,  batch_size: 1,  input: nil, schematic_id: 119, name: 'Wetware Mainframe')
