require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

  Exclude:
    - Rakefile
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*

  TargetRubyVersion: 3.3.5

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Exclude:
    - db/seeds.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  # Exclude:
  #   - config/routes.rb
  #   - db/*
  AllowedMethods:
    - configure
    # Specs
    - describe
    - shared_examples_for

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Exclude:
    - db/migrate/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/DangerousColumnNames:
  Exclude:
    - db/migrate/20200927060147_create_planetary_commodities.rb
    - db/migrate/20201211043127_create_items.rb
    - db/migrate/20220724172852_create_regions.rb
    - db/migrate/20220724173103_create_constellations.rb
    - db/migrate/20220724173602_create_stars.rb
    - db/migrate/20220724192455_create_industry_jobs.rb

Rails/I18nLocaleTexts:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Exclude:
    - db/migrate/20220724191821_create_orders.rb

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed
