require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

  Exclude:
    - Rakefile
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*

  TargetRubyVersion: 3.0.0

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Exclude:
    - db/seeds.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - db/*
  IgnoredMethods:
    - configure
    - included  # Concerns
    - setup     # Because of devise

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Exclude:
    - db/migrate/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed
