Style/StringLiterals:
  Exclude:
    - Capfile
    - Gemfile
    - app/controllers/users/sessions_controller.rb
    - app/helpers/esi_helper.rb
    - app/helpers/industry_helper.rb
    - app/helpers/market_orders_helper.rb
    - app/mailers/application_mailer.rb
    - app/models/character.rb
    - app/models/concerns/csv_importable.rb
    - app/models/esi.rb
    - app/models/industry_job.rb
    - app/models/planetary_colony.rb
    - app/models/user.rb
    - config.ru
    - config/application.rb
    - config/boot.rb
    - config/deploy.rb
    - config/deploy/production.rb
    - config/environment.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/test.rb
    - config/initializers/assets.rb
    - config/initializers/backtrace_silencers.rb
    - config/initializers/devise.rb
    - config/initializers/inflections.rb
    - config/puma.rb
    - config/routes.rb
    - config/spring.rb
    - db/migrate/20220724192847_create_planetary_colonies.rb
    - db/seeds.rb
    - lib/tasks/export_planetary_commodities.rake
    - lib/tasks/export_stars.rake
    - lib/tasks/orders.rake
    - spec/factories/character_factory.rb
    - spec/factories/industry_job_factory.rb
    - spec/factories/planetary_colony_factory.rb
    - spec/models/character_spec.rb
    - spec/models/constellation_spec.rb
    - spec/models/industry_job_spec.rb
    - spec/models/item_spec.rb
    - spec/models/items_prices_spec.rb
    - spec/models/planetary_colony_spec.rb
    - spec/models/region_spec.rb
    - spec/models/star_spec.rb
    - spec/models/user_spec.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - spec/support/csv_importable.rb
