# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

PlanetaryCommodity.create(id: 2073, name: 'Microorganisms', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2267, name: 'Base Metals', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2268, name: 'Aqueous Liquids', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2270, name: 'Noble Metals', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2272, name: 'Heavy Metals', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2286, name: 'Planktic Colonies', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2287, name: 'Complex Organisms', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2288, name: 'Carbon Compounds', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2305, name: 'Autotrophs', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2306, name: 'Non-CS Crystals', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2307, name: 'Felsic Magma', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2308, name: 'Suspended Plasma', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2309, name: 'Ionic Solutions', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2310, name: 'Noble Gas', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2311, name: 'Reactive Gas', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2389, name: 'Plasmoids', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2390, name: 'Electrolytes', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2392, name: 'Oxidizing Compound', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2393, name: 'Bacteria', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2395, name: 'Proteins', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2396, name: 'Biofuels', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2397, name: 'Industrial Fibers', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2398, name: 'Reactive Metals', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2399, name: 'Precious Metals', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2400, name: 'Toxic Metals', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2401, name: 'Chiral Structures', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 3645, name: 'Water', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 3683, name: 'Oxygen', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 3779, name: 'Biomass', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 9828, name: 'Silicon', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 44, name: 'Enriched Uranium', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2312, name: 'Supertensile Plastics', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2317, name: 'Oxides', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2319, name: 'Test Cultures', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2321, name: 'Polyaramids', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2327, name: 'Microfiber Shielding', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2328, name: 'Water-Cooled CPU', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2329, name: 'Biocells', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2463, name: 'Nanites', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3689, name: 'Mechanical Parts', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3691, name: 'Synthetic Oil', tier: 9, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3693, name: 'Fertilizer', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3695, name: 'Polytextiles', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3697, name: 'Silicate Glass', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3725, name: 'Livestock', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3775, name: 'Viral Agent', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3828, name: 'Construction Blocks', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 9830, name: 'Rocket Fuel', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 9832, name: 'Coolant', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 9836, name: 'Consumer Electronics', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 9838, name: 'Superconductors', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 9840, name: 'Transmitter', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 9842, name: 'Miniature Electronics', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 15_317, name: 'Genetically Enhanced Livestock', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2344, name: 'Condensates', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2345, name: 'Camera Drones', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2346, name: 'Synthetic Synapses', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2348, name: 'Gel-Matrix Biopaste', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2349, name: 'Supercomputers', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2351, name: 'Smartfab Units', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2352, name: 'Nuclear Reactors', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2354, name: 'Neocoms', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2358, name: 'Biotech Research Reports', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2360, name: 'Industrial Explosives', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2361, name: 'Hermetic Membranes', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2366, name: 'Hazmat Detection Systems', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2367, name: 'Cryoprotectant Solution', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 9834, name: 'Guidance Systems', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 9846, name: 'Planetary Vehicles', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 9848, name: 'Robotics', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 12_836, name: 'Transcranial Microcontrollers', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 17_136, name: 'Ukomi Superconductors', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 17_392, name: 'Data Chips', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 17_898, name: 'High-Tech Transmitters', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 28_974, name: 'Vaccines', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2867, name: 'Broadcast Node', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2868, name: 'Integrity Response Drones', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2869, name: 'Nano-Factory', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2870, name: 'Organic Mortar Applicators', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2871, name: 'Recursive Computing Module', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2872, name: 'Self-Harmonizing Power Core', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2875, name: 'Sterile Conduits', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2876, name: 'Wetware Mainframe', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)

Star.create(id: 30_000_142, name: 'Jita', constellation_id: 0, region_id: 0)
Star.create(id: 30_002_187, name: 'Amarr', constellation_id: 0, region_id: 0)
Star.create(id: 30_002_659, name: 'Dodixie', constellation_id: 0, region_id: 0)
Star.create(id: 30_002_874, name: 'R1O-GN', constellation_id: 0, region_id: 0)
