# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

PlanetaryCommodity.create(id: 2073, name: 'Microorganisms', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2267, name: 'Base Metals', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2268, name: 'Aqueous Liquids', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2270, name: 'Noble Metals', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2272, name: 'Heavy Metals', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2286, name: 'Planktic Colonies', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2287, name: 'Complex Organisms', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2288, name: 'Carbon Compounds', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2305, name: 'Autotrophs', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2306, name: 'Non-CS Crystals', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2307, name: 'Felsic Magma', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2308, name: 'Suspended Plasma', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2309, name: 'Ionic Solutions', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2310, name: 'Noble Gas', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2311, name: 'Reactive Gas', tier: 0, volume: 0.1e-1, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2389, schematic_id: 122, name: 'Plasmoids', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2390, schematic_id: 123, name: 'Electrolytes', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2392, schematic_id: 125, name: 'Oxidizing Compound', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2393, schematic_id: 131, name: 'Bacteria', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2395, schematic_id: 133, name: 'Proteins', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2396, schematic_id: 134, name: 'Biofuels', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2397, schematic_id: 135, name: 'Industrial Fibers', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2398, schematic_id: 126, name: 'Reactive Metals', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2399, schematic_id: 127, name: 'Precious Metals', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2400, schematic_id: 128, name: 'Toxic Metals', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 2401, schematic_id: 129, name: 'Chiral Structures', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 3645, schematic_id: 72, name: 'Water', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 3683, schematic_id: 124, name: 'Oxygen', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 3779, schematic_id: 132, name: 'Biomass', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 9828, schematic_id: 130, name: 'Silicon', tier: 1, volume: 0.38e0, batch_size: 20, input: nil)
PlanetaryCommodity.create(id: 44, schematic_id: 75, name: 'Enriched Uranium', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2312, schematic_id: 87, name: 'Supertensile Plastics', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2317, schematic_id: 69, name: 'Oxides', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2319, schematic_id: 86, name: 'Test Cultures', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2321, schematic_id: 88, name: 'Polyaramids', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2327, schematic_id: 80, name: 'Microfiber Shielding', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2328, schematic_id: 121, name: 'Water-Cooled CPU', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2329, schematic_id: 79, name: 'Biocells', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2463, schematic_id: 78, name: 'Nanites', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3689, schematic_id: 73, name: 'Mechanical Parts', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3691, schematic_id: 68, name: 'Synthetic Oil', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3693, schematic_id: 82, name: 'Fertilizer', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3695, schematic_id: 85, name: 'Polytextiles', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3697, schematic_id: 70, name: 'Silicate Glass', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3725, schematic_id: 84, name: 'Livestock', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3775, schematic_id: 81, name: 'Viral Agent', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 3828, schematic_id: 74, name: 'Construction Blocks', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 9830, schematic_id: 67, name: 'Rocket Fuel', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 9832, schematic_id: 66, name: 'Coolant', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 9836, schematic_id: 76, name: 'Consumer Electronics', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 9838, schematic_id: 65, name: 'Superconductors', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 9840, schematic_id: 71, name: 'Transmitter', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 9842, schematic_id: 77, name: 'Miniature Electronics', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 15_317, schematic_id: 83, name: 'Genetically Enhanced Livestock', tier: 2, volume: 0.15e1, batch_size: 5, input: nil)
PlanetaryCommodity.create(id: 2344, schematic_id: 90, name: 'Condensates', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2345, schematic_id: 91, name: 'Camera Drones', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2346, schematic_id: 92, name: 'Synthetic Synapses', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2348, schematic_id: 95, name: 'Gel-Matrix Biopaste', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2349, schematic_id: 96, name: 'Supercomputers', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2351, schematic_id: 98, name: 'Smartfab Units', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2352, schematic_id: 99, name: 'Nuclear Reactors', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2354, schematic_id: 102, name: 'Neocoms', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2358, schematic_id: 104, name: 'Biotech Research Reports', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2360, schematic_id: 106, name: 'Industrial Explosives', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2361, schematic_id: 107, name: 'Hermetic Membranes', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2366, schematic_id: 110, name: 'Hazmat Detection Systems', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2367, schematic_id: 111, name: 'Cryoprotectant Solution', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 9834, schematic_id: 100, name: 'Guidance Systems', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 9846, schematic_id: 103, name: 'Planetary Vehicles', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 9848, schematic_id: 97, name: 'Robotics', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 12_836, schematic_id: 108, name: 'Transcranial Microcontrollers', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 17_136, schematic_id: 89, name: 'Ukomi Superconductors', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 17_392, schematic_id: 109, name: 'Data Chips', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 17_898, schematic_id: 94, name: 'High-Tech Transmitters', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 28_974, schematic_id: 105, name: 'Vaccines', tier: 3, volume: 0.6e1, batch_size: 3, input: nil)
PlanetaryCommodity.create(id: 2867, schematic_id: 117, name: 'Broadcast Node', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2868, schematic_id: 118, name: 'Integrity Response Drones', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2869, schematic_id: 114, name: 'Nano-Factory', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2870, schematic_id: 112, name: 'Organic Mortar Applicators', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2871, schematic_id: 116, name: 'Recursive Computing Module', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2872, schematic_id: 115, name: 'Self-Harmonizing Power Core', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2875, schematic_id: 113, name: 'Sterile Conduits', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)
PlanetaryCommodity.create(id: 2876, schematic_id: 119, name: 'Wetware Mainframe', tier: 4, volume: 0.1e3, batch_size: 1, input: nil)

Star.create(id: 30_000_142, name: 'Jita', constellation_id: 0, region_id: 0)
Star.create(id: 30_002_187, name: 'Amarr', constellation_id: 0, region_id: 0)
Star.create(id: 30_002_659, name: 'Dodixie', constellation_id: 0, region_id: 0)
Star.create(id: 30_002_874, name: 'R1O-GN', constellation_id: 0, region_id: 0)
